/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#ifndef _LOCAL_BROKER_H_
#define _LOCAL_BROKER_H_

#include <iostream>
#include <string>

class LocalBroker {
private:
	std::string nombre_broker_conectado;
	std::string nombre_aeropuerto;

public:
	LocalBroker();
	virtual ~LocalBroker();

	void registrar_aplicacion(std::string nombre_aplicacion, int numero);

	void tomar_mutex(std::string nombre_mutex);

	void test_imprimir_mensaje(const std::string & mensaje);
};

#endif /* !_LOCAL_BROKER_H_ */
