/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#include "torre_de_control.h"

bool_t
xdr_Operandos (XDR *xdrs, Operandos *objp)
{
	register int32_t *buf = NULL;
   buf = buf;

	 if (!xdr_int (xdrs, &objp->num_vuelo))
		 return FALSE;
	 if (!xdr_int (xdrs, &objp->num_zona))
		 return FALSE;
	return TRUE;
}
