/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#ifndef _TORRE_DE_CONTROL_H_RPCGEN
#define _TORRE_DE_CONTROL_H_RPCGEN

#include <rpc/rpc.h>


#ifdef __cplusplus
extern "C" {
#endif


struct Operandos {
	int num_vuelo;
	int num_zona;
};
typedef struct Operandos Operandos;

#define TORREDECONTROLPROG 0x20000001
#define TORREDECONTROLVERS 1

#if defined(__STDC__) || defined(__cplusplus)
#define ASIGNAR_VUELO 0
extern  void * asignar_vuelo_1(Operandos *, CLIENT *);
extern  void * asignar_vuelo_1_svc(Operandos *, struct svc_req *);
#define DESASIGNAR_VUELO 1
extern  void * desasignar_vuelo_1(int *, CLIENT *);
extern  void * desasignar_vuelo_1_svc(int *, struct svc_req *);
#define GET_ZONA 2
extern  int * get_zona_1(int *, CLIENT *);
extern  int * get_zona_1_svc(int *, struct svc_req *);
extern int torredecontrolprog_1_freeresult (SVCXPRT *, xdrproc_t, caddr_t);

#else /* K&R C */
#define ASIGNAR_VUELO 0
extern  void * asignar_vuelo_1();
extern  void * asignar_vuelo_1_svc();
#define DESASIGNAR_VUELO 1
extern  void * desasignar_vuelo_1();
extern  void * desasignar_vuelo_1_svc();
#define GET_ZONA 2
extern  int * get_zona_1();
extern  int * get_zona_1_svc();
extern int torredecontrolprog_1_freeresult ();
#endif /* K&R C */

/* the xdr functions */

#if defined(__STDC__) || defined(__cplusplus)
extern  bool_t xdr_Operandos (XDR *, Operandos*);

#else /* K&R C */
extern bool_t xdr_Operandos ();

#endif /* K&R C */

#ifdef __cplusplus
}
#endif

#endif /* !_TORRE_DE_CONTROL_H_RPCGEN */
