#ifndef CONSTANTS_H_
#define CONSTANTS_H_

#define CAPACIDAD_CINTA_CHECKIN 3
#define PUESTOS_CHECKIN_POR_CINTA 1
#define ROBOT_CHECKIN_POR_CINTA 1

#define SLEEP_PUESTO_CHECKIN 3
#define SLEEP_ROBOT_CHECKIN 20

#define TIEMPO_SIMULACION 100
#endif
