/*
 * debug_processes.h
 *
 *  Created on: 05/03/2013
 *      Author: gonzalo
 */

#ifndef DEBUG_PROCESSES_H_
#define DEBUG_PROCESSES_H_

// TODOS EN 0 PARA LA ENTREGA FINAL

#define DEBUG_ROBOT_CHECKIN_EXTRAE_CINTA_CHECKIN 0
#define DEBUG_ROBOT_CHECKIN_COLOCA_CINTA_SCANNER 0

#define DEBUG_ROBOT_SCANNER_EXTRAE_CINTA_SCANNER 0
#define DEBUG_ROBOT_SCANNER_COLOCA_CINTA_PPAL 0

#define DEBUG_ROBOT_DESPACHO_EXTRAE_CINTA_PPAL 0
#define DEBUG_ROBOT_DESPACHO_COLOCA_CINTA_CONTENEDOR 0



#endif /* DEBUG_PROCESSES_H_ */
