/*
 * debug_flags.h
 *
 *  Created on: 08/03/2013
 *      Author: gonzalo
 */

#ifndef DEBUG_FLAGS_H_
#define DEBUG_FLAGS_H_

#define DEBUG_CINTA_CHECKIN 0
#define DEBUG_CINTA_PRINCIPAL 0
#define DEBUG_CINTA_CONTENEDOR 0
#define DEBUG_CINTA_SCANNER 0

#define DEBUG_PUESTO_CHECKIN_COLOCA_CINTA_CHECKIN 0

#define DEBUG_ROBOT_CHECKIN_EXTRAE_CINTA_CHECKIN 0
#define DEBUG_ROBOT_CHECKIN_COLOCA_CINTA_SCANNER 0

#define DEBUG_ROBOT_SCANNER_EXTRAE_CINTA_SCANNER 0
#define DEBUG_ROBOT_SCANNER_COLOCA_CINTA_PPAL 0

#define DEBUG_ROBOT_DESPACHO_EXTRAE_CINTA_PPAL 0
#define DEBUG_ROBOT_DESPACHO_COLOCA_CINTA_CONTENEDOR 0

#define DEBUG_ROBOT_CARGA_EXTRAE_CINTA_CONTENEDOR 0

#define DEBUG_ROBOT_CONTROL_EXTRAE_CINTA_PRINCIPAL 0
#define DEBUG_ROBOT_CONTROL_COLOCA_CINTA_PRINCIPAL 0

#define DEBUG_LOCAL_BROKER_COMM 0
#define DEBUG_CLIENT_HANDLER 0
#define DEBUG_TOKEN_MANAGER 0

#define DEBUG_MEMORIA_DISTRIBUIDA 0

#endif /* DEBUG_FLAGS_H_ */
